---
- name: Backup Cisco Devices
  hosts: routers
  gather_facts: true
  connection: network_cli 

  tasks:
    - name: Get Ansible Date/Time Facts
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
    
    - name: Store Date/Time as Fact
      set_fact: 
        DTG: "{{ ansible_date_time.date }}"

    - name: Task 1 - Backup Cisco Configuration
      cisco.ios.ios_config:
        backup: true
        backup_options:
          filename: "{{ inventory_hostname }}-{{ DTG }}_running-config.cfg"
          dir_path: ./backups