---
  - name: Backup Cisco running configuration and push to GitHub
    hosts: routers
    gather_facts: no
    tasks:
      - name: Retrieve running configuration
        cisco.ios.ios_config:
          backup: yes
        register: config_backup
  
      - name: Save configuration to a file
        copy:
          src: "{{ config_backup.backup_path }}"
          dest: "/tmp/{{ inventory_hostname }}-running-config.cfg"
          remote_src: no
        delegate_to: localhost
      
      - name: Check if source file exists
        stat:
          path: "/tmp/{{ inventory_hostname }}-running-config.cfg"
        register: source_file
        delegate_to: localhost
      
      - name: Debug source file status
        debug:
          var: source_file

  
      # - name: Prepare Git environment
      #   block:
      #     - name: Ensure git is installed
      #       ansible.builtin.package:
      #         name: git
      #         state: present
  
      - name: Push configuration to GitHub
        block:
          - name: Clone the repo if not present
            ansible.builtin.git:
              repo: 'https://github.com/ttweed98/aap_templates'
              dest: /tmp/aap_templates
              clone: yes
              update: no
            delegate_to: localhost
          
          - name: Ensure Backup Directory Exists
            file:
              path: "/tmp/aap_templates/backups/"
              state: directory
              mode: '0755'
            delegate_to: localhost
  
          - name: Copy configuration to repo
            become: yes
            copy:
              src: "/tmp/{{ inventory_hostname }}-running-config.cfg"
              dest: "/tmp/aap_templates/backups/{{ inventory_hostname }}-running-config.cfg"
              remote_src: no
            delegate_to: localhost
  
          - name: Commit and push changes
            shell: |
              cd /tmp/aap_templates
              git add backups/{{ inventory_hostname }}-running-config.cfg
              git commit -m "Backup running config for {{ inventory_hostname }}"
              git push origin main
            environment:
              GIT_AUTHOR_NAME: "Tony Tweed"
              GIT_AUTHOR_EMAIL: "ttweed98@gmail.com"
              GIT_COMMITTER_NAME: "Tony Tweed"
              GIT_COMMITTER_EMAIL: "ttweed98@gmail.com"
            delegate_to: localhost
  
      # Optional cleanup task for temporary files if needed
      - name: Clean up temporary files
        file:
          path: "/tmp/{{ inventory_hostname }}-running-config.cfg"
          state: absent
        delegate_to: localhost
