---
- name: Gather Facts from Cisco Router
  hosts: routers
  gather_facts: false
  connection: network_cli 

  tasks: 
    - name: Gather facts 
      cisco.ios.ios_facts:
        gather_subset: all
    
    - name: Print facts
      debug:
        msg: 
          - "The IOS image is {{ ansible_facts['net_image'] }}"
          - "The IOS version is {{ ansible_facts['net_version'] }}"
          - "The Serial is {{ ansible_facts['net_serialnum'] }}"
          - "The model is {{ ansible_facts['net_model'] }}"
          - "The ip addresses are {{ ansible_facts['net_all_ipv4_addresses'] }}"